apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: ibm-mq
spec:

  pki:
    keys:
      - name: certificate
        secret:
          items:
            - tls.key
            - tls.crt
          secretName: __env____qmgrname__-cert
    trust:
      - name: ca
        secret:
          items:
            - ca.crt
          secretName: __env____qmgrname__-cert

  queueManager:
      resources:
        limits:
          cpu: 800m
        requests:
          cpu: 800m
      name: __ENV____QMGRNAME__
      availability:
        type: NativeHA
        updateStrategy: RollingUpdate
      storage:
        queueManager:
          size: 2Gi
          type: persistent-claim
        defaultDeleteClaim: true
      mqsc:
      - configMap:
          name: __qmgrname__-mqsc-configmap
          items:
            - static.mqsc
  template:
    pod:
      volumes:
        - name: config-volume-scripts
          configMap:
            name: __qmgrname__-scripts-configmap
            defaultMode: 0777
        - name: dynamic-config-volume-mqsc
          configMap:
            name: __qmgrname__-dynamic-mqsc-configmap
            defaultMode: 0777

      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
          volumeMounts:
          - name: config-volume-scripts
            mountPath: /mq-config
            readOnly: true
          - name: dynamic-config-volume-mqsc
            mountPath: /dyn-mq-config-mqsc
            readOnly: true

