apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: ibm-mq
spec:
  license:
    accept: true
    license: L-APIG-CAUEQC
    use: Development
  version: 9.3.2.1-r2
  queueManager:
    image: image-registry.openshift-image-registry.svc:5000/mq-demo/mq-prometheus:1.0.3

  
